### Create a book
POST https://book-list-back-end.onrender.com/books HTTP/1.1
Content-Type: application/json

{
  "title": "Test 1"
}

### Get the list of books
GET https://book-list-back-end.onrender.com/books HTTP/1.1
Content-Type: application/json

### Get a particular book by it's id
GET https://book-list-back-end.onrender.com/books HTTP/1.1
Content-Type: application/json

### Edit a particular book by it's id
PUT https://book-list-back-end.onrender.com/books HTTP/1.1
Content-Type: application/json

{
  "title": "EDITED"
}

### Delete a particular book by it's id
DELETE https://book-list-back-end.onrender.com/books HTTP/1.1
Content-Type: application/json